#!/usr/bin/env python

""" This is the main executable files for systems where setuptools
is not available. On POSIX systems it should be put in /usr/bin or 
/usr/local/bin. """

from findsilence.main import main
main()

