#!/usr/bin/env python

""" This is the main GUI executable files for systems where setuptools
is not available. On POSIX systems it should be put in /usr/bin or 
/usr/local/bin. """

from findsilence.gui import create_gui
create_gui()

